import type { Metadata } from 'next'
import { Inter as FontSans } from 'next/font/google'
import Link from 'next/link'



import './globals.css'
import { Card, CardContent } from '@/components/ui/card'

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-amber-50 font-sans antialiased">

        <header className="sticky top-0 z-50 w-full bg-white shadow-md">
          <div className="container mx-auto py-2">
            <Link href="/" className="block">
              <h1 className="text-2xl font-bold text-center">Watch Tonight</h1>
            </Link>
          </div>
        </header>
        <div className="container mx-auto py-6">

          {children}

        </div>
      </body>
    </html>
  )
}
